SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

CREATE DATABASE IF NOT EXISTS hymperia DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE hymperia;

SOURCE 'creation.sql';
SOURCE 'insertion.sql';

DROP TABLE IF EXISTS __efmigrationshistory;
CREATE TABLE IF NOT EXISTS __efmigrationshistory (
  MigrationId VARCHAR(95) NOT NULL,
  ProductVersion VARCHAR(32) NOT NULL,
  PRIMARY KEY (MigrationId)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO __efmigrationshistory VALUES
('20180926161335_InitialDatabase', '2.2.0-preview1-35029'),
('20180927194038_Rotation', '2.2.0-preview1-35029');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
