// <auto-generated />
using Hymperia.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hymperia.Model.Migrations
{
  [DbContext(typeof(LocalizationContext))]
  [Migration("20181023181750_Localization")]
  partial class Localization
  {
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "2.2.0-preview2-35157")
          .HasAnnotation("Relational:MaxIdentifierLength", 64);

      modelBuilder.Entity("Hymperia.Model.Localization.LocalizedMateriau", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd();

            b.Property<string>("CultureKey")
                      .IsRequired();

            b.Property<string>("Nom")
                      .IsRequired();

            b.Property<string>("StringKey")
                      .IsRequired();

            b.HasKey("Id");

            b.HasAlternateKey("CultureKey", "Nom");

            b.HasAlternateKey("StringKey", "CultureKey");

            b.ToTable("Materiaux");
          });
#pragma warning restore 612, 618
    }
  }
}
