// <auto-generated />
using System;
using Hymperia.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hymperia.Model.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview1-35029")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Hymperia.Model.Modeles.Acces", b =>
                {
                    b.Property<int>("IdProjet");

                    b.Property<int>("IdUtilisateur");

                    b.Property<string>("DroitDAcces")
                        .IsRequired();

                    b.HasKey("IdProjet", "IdUtilisateur");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("Acces");
                });

            modelBuilder.Entity("Hymperia.Model.Modeles.Forme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int>("IdMateriau");

                    b.Property<int?>("IdProjet");

                    b.HasKey("Id");

                    b.HasIndex("IdMateriau");

                    b.HasIndex("IdProjet");

                    b.ToTable("Formes");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Forme");
                });

            modelBuilder.Entity("Hymperia.Model.Modeles.Materiau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nom")
                        .IsRequired();

                    b.Property<double>("Prix");

                    b.HasKey("Id");

                    b.HasAlternateKey("Nom");

                    b.ToTable("Materiaux");
                });

            modelBuilder.Entity("Hymperia.Model.Modeles.Projet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nom")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasAlternateKey("Nom");

                    b.ToTable("Projets");
                });

            modelBuilder.Entity("Hymperia.Model.Modeles.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MotDePasse")
                        .IsRequired();

                    b.Property<string>("Nom")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasAlternateKey("Nom");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("Hymperia.Model.Modeles.Cone", b =>
                {
                    b.HasBaseType("Hymperia.Model.Modeles.Forme");

                    b.Property<double>("Hauteur");

                    b.Property<string>("Origine");

                    b.Property<double>("RayonBase");

                    b.Property<double>("RayonTop");

                    b.Property<int>("ThetaDiv");

                    b.HasDiscriminator().HasValue("Cone");
                });

            modelBuilder.Entity("Hymperia.Model.Modeles.Cylindre", b =>
                {
                    b.HasBaseType("Hymperia.Model.Modeles.Forme");

                    b.Property<double>("Diametre");

                    b.Property<double>("InnerDiametre");

                    b.Property<string>("Point1");

                    b.Property<string>("Point2");

                    b.Property<int>("ThetaDiv")
                        .HasColumnName("Cylindre_ThetaDiv");

                    b.HasDiscriminator().HasValue("Cylindre");
                });

            modelBuilder.Entity("Hymperia.Model.Modeles.Ellipsoide", b =>
                {
                    b.HasBaseType("Hymperia.Model.Modeles.Forme");

                    b.Property<string>("Centre");

                    b.Property<int>("PhiDiv");

                    b.Property<double>("RayonX");

                    b.Property<double>("RayonY");

                    b.Property<double>("RayonZ");

                    b.Property<int>("ThetaDiv")
                        .HasColumnName("Ellipsoide_ThetaDiv");

                    b.HasDiscriminator().HasValue("Ellipsoide");
                });

            modelBuilder.Entity("Hymperia.Model.Modeles.PrismeRectangulaire", b =>
                {
                    b.HasBaseType("Hymperia.Model.Modeles.Forme");

                    b.Property<string>("Centre")
                        .HasColumnName("PrismeRectangulaire_Centre");

                    b.Property<double>("Hauteur")
                        .HasColumnName("PrismeRectangulaire_Hauteur");

                    b.Property<double>("Largeur");

                    b.Property<double>("Longueur");

                    b.HasDiscriminator().HasValue("PrismeRectangulaire");
                });

            modelBuilder.Entity("Hymperia.Model.Modeles.Acces", b =>
                {
                    b.HasOne("Hymperia.Model.Modeles.Projet", "Projet")
                        .WithMany()
                        .HasForeignKey("IdProjet")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hymperia.Model.Modeles.Utilisateur", "Utilisateur")
                        .WithMany("_Acces")
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hymperia.Model.Modeles.Forme", b =>
                {
                    b.HasOne("Hymperia.Model.Modeles.Materiau", "Materiau")
                        .WithMany()
                        .HasForeignKey("IdMateriau")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hymperia.Model.Modeles.Projet")
                        .WithMany("_Formes")
                        .HasForeignKey("IdProjet");
                });
#pragma warning restore 612, 618
        }
    }
}
