// <auto-generated />
using Hymperia.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hymperia.Model.Migrations
{
  [DbContext(typeof(LocalizationContext))]
  partial class LocalizationContextModelSnapshot : ModelSnapshot
  {
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
          .HasAnnotation("Relational:MaxIdentifierLength", 64);

      modelBuilder.Entity("Hymperia.Model.Localization.LocalizedMateriau", b =>
          {
            b.Property<string>("StringKey")
                      .HasMaxLength(100);

            b.Property<string>("CultureKey")
                      .HasMaxLength(5);

            b.Property<string>("Nom")
                      .IsRequired()
                      .HasMaxLength(100);

            b.HasKey("StringKey", "CultureKey");

            b.HasAlternateKey("CultureKey", "Nom");

            b.ToTable("Materiaux");
          });
#pragma warning restore 612, 618
    }
  }
}
