// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace Hymperia.Model.Migrations
{
  [DbContext(typeof(LocalizationContext))]
  partial class LocalizationContextModelSnapshot : ModelSnapshot
  {
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "2.2.0-preview3-35497")
          .HasAnnotation("Relational:MaxIdentifierLength", 64);

      modelBuilder.Entity("Hymperia.Model.Localization.LocalizedMateriau", b =>
          {
            b.Property<string>("StringKey");

            b.Property<string>("CultureKey");

            b.Property<string>("Nom")
                      .IsRequired();

            b.HasKey("StringKey", "CultureKey");

            b.HasAlternateKey("CultureKey", "Nom");

            b.ToTable("Materiaux");
          });
#pragma warning restore 612, 618
    }
  }
}
